#ifndef PRIORITIES_H
#define PRIORITIES_H

#define SD_CARD_MANAGER_PRIORITY 5
#define FAN_CONTROLLER_PRIORITY 5
#define VISUALISER_PRIORITY 5
#define CONSOLE_PRIORITY 4
#define ESPNOW_COMMAND_HANDLER_PRIORITY 5

#endif